name: nexly
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  image_picker: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.5+1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  url_launcher: ^6.3.0
  share_plus: ^10.1.4
  social_sharing_plus: ^1.2.3
  flutter_secure_storage: ^9.2.4
  flutter_riverpod: ^2.5.1
  flutter_launcher_icons: ^0.13.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

    - assets/icons/index_frame/
    - assets/icons/new_post/
    - assets/images/landscape/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true